# Generated by Django 2.2.4 on 2020-12-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubc', '0001_initial'),
        ('prv', '__first__'),
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacionesProveedorVista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=500)),
                ('id_proveedor', models.IntegerField()),
                ('nombres', models.CharField(max_length=500)),
                ('apellidos', models.CharField(max_length=500)),
                ('pais_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_operaciones_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacionesTallerVista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('username', models.CharField(max_length=500)),
                ('id_taller', models.IntegerField()),
                ('nombre_taller', models.CharField(max_length=500)),
                ('pais_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_operaciones_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectoresTallerVista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sector', models.IntegerField()),
                ('nombre', models.CharField(max_length=500)),
                ('id_taller', models.IntegerField()),
                ('nombre_taller', models.CharField(max_length=500)),
                ('pais_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_sectores_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonasProveedorVista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zona', models.IntegerField()),
                ('nombre', models.CharField(max_length=500)),
                ('id_proveedor', models.IntegerField()),
                ('nombres', models.CharField(max_length=500)),
                ('apellidos', models.CharField(max_length=500)),
                ('pais_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_zonas_proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonasTallerVista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zona', models.IntegerField()),
                ('nombre', models.CharField(max_length=500)),
                ('id_taller', models.IntegerField()),
                ('nombre_taller', models.CharField(max_length=500)),
                ('pais_id', models.IntegerField()),
            ],
            options={
                'db_table': 'vw_zonas_taller',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionReporteUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_crea', models.IntegerField(blank=True, null=True)),
                ('grupo_empresarial_id', models.IntegerField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Roles')),
            ],
            options={
                'permissions': [('envio_reporte_user', 'Permiso para reporte de conexion')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionApiSMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
            ],
            options={
                'permissions': [('envio_sms', 'Permiso para envio de sms')],
            },
        ),
        migrations.CreateModel(
            name='ConfigUtilidadTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_usuario_op', models.IntegerField(default=1)),
                ('usuario_op', models.CharField(max_length=200)),
                ('id_taller', models.IntegerField(default=1)),
                ('taller', models.CharField(max_length=200)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
            ],
            options={
                'unique_together': {('id_usuario_op', 'id_taller')},
            },
        ),
        migrations.CreateModel(
            name='ConfigUtilidadProveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_usuario_op', models.IntegerField(default=1)),
                ('usuario_op', models.CharField(max_length=200)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('utilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prv.Proveedores')),
            ],
            options={
                'unique_together': {('id_usuario_op', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='ConfigGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('empresa', models.CharField(max_length=100)),
                ('utilidad_sobre_taller', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('limite_venta', models.IntegerField(default=0)),
                ('costo_gramo_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('precio_gramo_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('utilidad_sobre_base', models.DecimalField(decimal_places=8, default=0, max_digits=12)),
                ('aut_externo', models.BooleanField(default=False)),
                ('descuento_max', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('prct_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('configurado', models.BooleanField(default=False)),
                ('origen_material', models.IntegerField(default=1)),
                ('anticipo_fabricacion', models.BooleanField(default=True)),
                ('envio_material', models.BooleanField(default=True)),
                ('comprobante_env', models.BooleanField(default=True)),
                ('envio_incluido', models.BooleanField(default=False)),
                ('factura_taller', models.BooleanField(default=True)),
                ('cta_por_pagar', models.BooleanField(default=True)),
                ('orden_compra', models.BooleanField(default=True)),
                ('tipo_precio_predefinido', models.IntegerField(blank=True, null=True)),
                ('precio_gramo_final', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='logotipos/')),
                ('politicas_pdf', models.FileField(blank=True, null=True, upload_to='politicas/')),
                ('politicas_doc', models.FileField(blank=True, null=True, upload_to='politicas/')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
            ],
            options={
                'unique_together': {('pais', 'empresa')},
            },
        ),
    ]
