# Generated by Django 2.2.4 on 2020-12-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionreporteusuarios',
            name='taller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
