# Generated by Django 2.2.4 on 2021-02-02 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0002_configuracionreporteusuarios_taller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticasComerciales',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_politica', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('ordenamiento', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfg.ConfigGeneral')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
