# Generated by Django 2.2.4 on 2021-02-02 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0003_politicascomerciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicascomerciales',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.GruposEmpresariales'),
        ),
    ]
