# Generated by Django 2.2.4 on 2020-12-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionTooltipOperaciones',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_tooltip', models.AutoField(primary_key=True, serialize=False)),
                ('campo_orden', models.CharField(max_length=100)),
                ('texto', models.CharField(help_text='texto de tooltip', max_length=50)),
                ('grupo', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=None)),
            ],
            options={
                'permissions': [('permiso_tooltip', 'Permiso para tooltip en Operaciones')],
            },
        ),
    ]
