# Generated by Django 2.2.4 on 2020-12-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0002_configuraciontooltipoperaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuraciontooltipoperaciones',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='configuraciontooltipoperaciones',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='configuraciontooltipoperaciones',
            name='usuario_crea',
        ),
        migrations.RemoveField(
            model_name='configuraciontooltipoperaciones',
            name='usuario_modifica',
        ),
        migrations.AlterField(
            model_name='configuraciontooltipoperaciones',
            name='estado',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='configuraciontooltipoperaciones',
            name='grupo',
            field=models.IntegerField(blank=True, help_text='grupo_empresarial de tooltip', null=True),
        ),
    ]
