# Generated by Django 2.2.4 on 2020-12-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0003_auto_20201207_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciontooltipoperaciones',
            name='pais',
            field=models.IntegerField(blank=True, help_text='pais realcionado al tooltip', null=True),
        ),
    ]
