# Generated by Django 2.2.4 on 2020-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0004_configuraciontooltipoperaciones_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrosasociados',
            name='grupo_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rubrosasociados',
            name='taller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
