# Generated by Django 2.2.4 on 2020-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0005_auto_20201209_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubrosasociados',
            name='grupo_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='rubrosasociados',
            name='taller_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
