# Generated by Django 2.2.4 on 2020-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0007_auto_20201214_0637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('estadisticas_admin', 'Ver estadisticas administrador'), ('pagos_aprobados', 'Ver pagos aprobados'), ('ver_comp_envio_op', 'Ver comprobante envio material'), ('ver_comp_envio_ta', 'Ver comprobante envio producto'), ('ver_factura', 'Ver factura de venta'), ('ver_detalle_costos', 'Ver detalle de costos'), ('ver_anticipo', 'Ver anticipo de fabricacion'), ('ver_factura_taller', 'Ver factura de taller'), ('ver_cta_por_pagar', 'Ver cuenta por pagar'), ('ver_orden_compra', 'Ver orden de compra'), ('pagar_factura', 'Pagar facturas'), ('enviar_producto', 'Enviar Producto'), ('finalizar_trabajo', 'Finalizar Trabajo'), ('iniciar_orden', 'Iniciar Trabajo'), ('anular_orden', 'Anular Orden')], 'verbose_name_plural': 'Ordenes de trabajo'},
        ),
    ]
