# Generated by Django 2.2.4 on 2021-01-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0009_auto_20201214_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenespiedras',
            name='diseño',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='id_orden',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
