# Generated by Django 2.2.4 on 2021-01-19 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0002_auto_20201214_0519'),
        ('ubc', '0001_initial'),
        ('trn', '0010_auto_20210113_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRechazoSolicitudOrdenes',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_obs_rechazo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_rechazo', models.CharField(help_text='texto a mostrar en modal', max_length=80)),
                ('observacion_rechazo', models.CharField(help_text='factor comun del rechazo', max_length=500)),
                ('grupo_empresarial', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='est.GruposEmpresariales')),
                ('pais', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
                ('taller', models.ForeignKey(blank=True, default=True, on_delete=django.db.models.deletion.CASCADE, to='est.Talleres')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
