# Generated by Django 2.2.4 on 2021-01-19 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0011_configuracionrechazosolicitudordenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='grupo_empresarial',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.GruposEmpresariales'),
        ),
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='pais',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises'),
        ),
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='taller',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Talleres'),
        ),
    ]
