# Generated by Django 2.2.4 on 2021-01-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0012_auto_20210119_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='rechazo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trn.ConfiguracionRechazoSolicitudOrdenes'),
        ),
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='grupo_empresarial',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.GruposEmpresariales'),
        ),
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='pais',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises'),
        ),
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='taller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='est.Talleres'),
        ),
    ]
