# Generated by Django 2.2.4 on 2021-01-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0013_auto_20210120_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='rechazo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trn.ConfiguracionRechazoSolicitudOrdenes'),
        ),
    ]
