# Generated by Django 2.2.4 on 2021-01-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0014_solicitudtrabajo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontooltipoperaciones',
            name='texto',
            field=models.CharField(help_text='texto de tooltip', max_length=200),
        ),
    ]
