# Generated by Django 2.2.4 on 2021-01-31 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0015_auto_20210122_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionrechazosolicitudordenes',
            options={'permissions': [('permiso_motivo_rechazo', 'Permiso para configurar motivos de rechazo.')]},
        ),
    ]
