# Generated by Django 2.2.4 on 2021-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0017_solicitudtrabajo_fabricacion_interna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='fabricacion_interna',
            field=models.BooleanField(default=0),
        ),
    ]
