# Generated by Django 2.2.4 on 2021-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0020_auto_20210206_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fabricacion_interna',
            field=models.BooleanField(default=0),
        ),
    ]
