# Generated by Django 2.2.4 on 2021-02-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0022_auto_20210217_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='origen_material_dividido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origen_dividido_orden', to='trn.OrigenMaterial'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='peso_cliente_divido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='peso_materia_dividida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
