# Generated by Django 2.2.4 on 2021-02-17 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0023_auto_20210217_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='peso_cliente_divido',
            new_name='peso_cliente_dividido',
        ),
    ]
