# Generated by Django 2.2.4 on 2021-02-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0024_auto_20210217_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudtrabajo',
            old_name='peso_cliente_divido',
            new_name='peso_cliente_dividido',
        ),
    ]
