# Generated by Django 2.2.4 on 2021-02-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0025_auto_20210217_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciontooltipoperaciones',
            name='estado',
            field=models.BooleanField(blank=True, default=1),
        ),
    ]
