# Generated by Django 2.2.4 on 2021-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0026_auto_20210219_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudtrabajo',
            name='detalle',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
