# Generated by Django 2.2.4 on 2021-02-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0027_auto_20210219_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudtrabajo',
            name='fabricacion_dividida',
            field=models.BooleanField(default=0),
        ),
    ]
