# Generated by Django 2.2.4 on 2021-02-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0028_solicitudtrabajo_fabricacion_dividida'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fabricacion_dividida',
            field=models.BooleanField(default=0),
        ),
    ]
