# Generated by Django 2.2.4 on 2021-02-26 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
        ('trn', '0029_ordentrabajo_fabricacion_dividida'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionrechazosolicitudordenes',
            name='estado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
    ]
