# Generated by Django 2.2.4 on 2021-02-26 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0030_configuracionrechazosolicitudordenes_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionrechazosolicitudordenes',
            name='estado',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados'),
        ),
    ]
