# Generated by Django 2.2.4 on 2021-03-11 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trn', '0032_auto_20210311_0952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('estadisticas_admin', 'Ver estadisticas administrador'), ('pagos_aprobados', 'Ver pagos aprobados'), ('ver_comp_envio_op', 'Ver comprobante envio material'), ('ver_comp_envio_ta', 'Ver comprobante envio producto'), ('envio_material_joyeria', 'Permiso para enviar el material al Taller'), ('ver_factura', 'Ver factura de venta'), ('ver_detalle_costos', 'Ver detalle de costos'), ('ver_anticipo', 'Ver anticipo de fabricacion'), ('ver_factura_taller', 'Ver factura de taller'), ('ver_cta_por_pagar', 'Ver cuenta por pagar'), ('ver_orden_compra', 'Ver orden de compra'), ('pagar_factura', 'Pagar facturas'), ('enviar_producto', 'Enviar Producto'), ('finalizar_trabajo', 'Finalizar Trabajo'), ('iniciar_orden', 'Iniciar Trabajo'), ('anular_orden', 'Anular Orden'), ('recibir_producto', 'Recibir Producto'), ('fabricacion_dividida_ordenes', 'Realizar Fabricaciones Divididas')], 'verbose_name_plural': 'Ordenes de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='solicitudtrabajo',
            options={'ordering': ['-fecha_creacion'], 'permissions': [('ver_detalle_costos_sol', 'Ver detalle de costos'), ('fabricacion_interna', 'Realizar Fabricaciones Internas'), ('fabricacion_dividida_solicitudes', 'Realizar Fabricaciones Divididas')], 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
