# Generated by Django 2.2.4 on 2020-12-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('iniciales', models.CharField(default=None, max_length=5)),
                ('aut_externo', models.BooleanField(default=False)),
                ('bandera', models.ImageField(blank=True, null=True, upload_to='banderas')),
                ('simbolo_moneda', models.CharField(max_length=10)),
                ('decimales', models.BooleanField(default=True)),
                ('zona_horaria', models.CharField(max_length=100)),
                ('documentos_obligatorios', models.BooleanField(default=True)),
                ('prefijo_cel', models.CharField(max_length=10)),
                ('separador_miles', models.CharField(max_length=5)),
                ('separador_decimal', models.CharField(max_length=5)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Regiones')),
            ],
            options={
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
            ],
            options={
                'verbose_name_plural': 'Localidades',
                'ordering': ['nombre'],
                'unique_together': {('pais', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Localidades')),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
                'unique_together': {('localidad', 'nombre')},
            },
        ),
    ]
