# Generated by Django 2.2.4 on 2020-12-04 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('est', '0001_initial'),
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.IntegerField(blank=True, null=True)),
                ('nombre_producto', models.CharField(max_length=500)),
                ('vista', models.BooleanField(default=False)),
                ('principal', models.BooleanField(default=False)),
                ('postergada', models.BooleanField(default=False)),
                ('id_transaccion', models.IntegerField(blank=True, null=True)),
                ('tipo_transaccion', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Talleres')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Tiendas')),
                ('usuario_genera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
