# Generated by Django 2.2.4 on 2020-12-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ntf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='tipo_notificacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
