"""
Django settings for sindri project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from django.utils.translation import ugettext_lazy as gettext

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'y73rg=3($bb)#v6%ak9p=bmfo$$dtl(gn^(^=6os&sn1=1h#9g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# DESARROLLO
SITIO = 'http://127.0.0.1:8000'

# PRUEBAS
# SITIO = 'https://pruebas.sindri.pro'

# PRODUCCION
# SITIO = 'https://sindri.pro'

DATA_UPLOAD_MAX_MEMORY_SIZE = None
FILE_UPLOAD_MAX_MEMORY_SIZE = 7456342

# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usr.apps.UsrConfig',  # usuarios
    'bases',  # paginas principales
    'ubc',  # ubicaciones
    'est',  # establecimientos
    'prv',  # proveedores
    'cfg',  # configuraciones
    'ctg',  # catálogo
    'clt',  # clientes
    'trn',  # transacciones
    'rosetta',  # traduccion idiomas
    'rest_framework',  # apirest
    'wso',  # websockets
    'ntf',  # notificaciones
    'dsh',  # dashboard
    'django_celery_beat',  # planificador personalizado Celery
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # i18n
]

ROOT_URLCONF = 'sindri.urls'
ASGI_APPLICATION = 'sindri.routing.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sindri.wsgi.application'

""" CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "asgiref.inmemory.ChannelLayer",
        "ROUTING": "realtime.routing.channel_routing",
    },
} """

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_rabbitmq.core.RabbitmqChannelLayer",
        "CONFIG": {
            "host": "amqp://guest:guest@127.0.0.1",
            # "ssl_context": ... (optional)
        },
    },
}


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'db_sindri_test',
#         'USER': 'root',
#         'PASSWORD': 'Innovacion2019',
#         'HOST': '127.0.0.1',
#         'PORT': '3306',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pruebas_sindri2',
        'USER': '',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation' +
            '.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation' +
            '.MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation' +
            '.CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation' +
            '.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    # 'django.contrib.auth.backends.ModelBackend',
    'usr.backends.EmailBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

LANGUAGES = (
    ('es-ec', gettext('Español Ecuador')),
    ('es-co', gettext('Español Colombia')),
    ('es-cl', gettext('Español Chile')),
    ('es-pe', gettext('Español Perú')),
    ('en-us', gettext('English USA')),
    ('pt-br', gettext('Português Brasil'))
)

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Carpeta de lenguajes
LOCALE_PATHS = (
    os.path.join(BASE_DIR, "locale"),
)

DEFAULT_CHARSET = 'utf-8'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

# Redireccionamiento
# LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# modificacion usuarios
AUTH_USER_MODEL = 'usr.Usuarios'

# Configuracion servidor de correos
EMAIL_HOST = 'smtp.mailgun.org'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'maildev'
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600  # Tiempo de caducidad de la sesión dado en segundos
SESSION_SAVE_EVERY_REQUEST = True
