# Generated by Django 2.2.4 on 2020-12-04 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubc', '0001_initial'),
        ('bases', '0001_initial'),
        ('est', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('identificacion', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=500)),
                ('telefono', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, null=True, unique=True)),
                ('tipo_usuario', models.IntegerField(default=1)),
                ('taller', models.IntegerField(null=True)),
                ('escala_peso', models.DecimalField(decimal_places=2, default=0.1, max_digits=15)),
                ('secuencia_ordenes', models.IntegerField(default=1)),
                ('secuencia_solicitudes', models.IntegerField(default=1)),
                ('costo_gramo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prct_impuestos', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ciudad', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ubc.Ciudades')),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Zonas')),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('pais', 'identificacion')},
            },
        ),
    ]
