# Generated by Django 2.2.4 on 2020-12-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposempresariales',
            name='comprobante_env',
            field=models.BooleanField(default=True, verbose_name='Comprobante de envío'),
        ),
    ]
