# Generated by Django 2.2.4 on 2021-02-01 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0002_auto_20201214_0519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talleres',
            options={'ordering': ['nombre'], 'permissions': [('prioridad_taller', 'Permisos para prioridades de talleres.')], 'verbose_name_plural': 'Talleres'},
        ),
    ]
