# Generated by Django 2.2.4 on 2021-02-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0003_auto_20210201_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposempresariales',
            options={'permissions': [('env_reportes', 'Permisos para configurar envio de reportes'), ('envio_material', 'Permiso para enviar material')]},
        ),
    ]
