# Generated by Django 2.2.4 on 2021-02-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('est', '0004_auto_20210206_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gruposempresariales',
            options={'permissions': [('env_reportes', 'Permisos para configurar envio de reportes')]},
        ),
    ]
