# Generated by Django 2.2.4 on 2020-12-04 20:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('est', '0001_initial'),
        ('bases', '0001_initial'),
        ('ubc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GruposPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosGrupos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'usr_usuarios_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('img_perfil', models.ImageField(blank=True, null=True, upload_to='perfil_img')),
                ('zona', models.IntegerField(default=None, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('pais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ubc.Paises')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_crea', models.IntegerField()),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modifica', models.IntegerField(blank=True, null=True)),
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('primario', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('zonal', models.BooleanField(default=False)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bases.Estados')),
                ('grupo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoUsuarios',
            fields=[
                ('id_tipo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_usuario', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Tipos usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuariosTiendas',
            fields=[
                ('id_usuario_tiendas', models.AutoField(primary_key=True, serialize=False)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Tiendas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosTalleres',
            fields=[
                ('id_usuario_taller', models.AutoField(primary_key=True, serialize=False)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Talleres')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosGruposEmpresariales',
            fields=[
                ('id_usuario_grupo_empresarial', models.AutoField(primary_key=True, serialize=False)),
                ('grupo_empresarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.GruposEmpresariales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RolesTalleres',
            fields=[
                ('id_rol_taller', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Roles')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.Talleres')),
            ],
        ),
        migrations.CreateModel(
            name='RolesGruposEmpresariales',
            fields=[
                ('id_rol_grupo_empresarial', models.AutoField(primary_key=True, serialize=False)),
                ('grupo_empresarial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='est.GruposEmpresariales')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Roles')),
            ],
        ),
        migrations.AddField(
            model_name='roles',
            name='tipo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.TipoUsuarios'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usr.Roles'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usr.TipoUsuarios'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='usuarios',
            unique_together={('pais', 'username')},
        ),
    ]
