# Generated by Django 2.2.4 on 2021-02-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='usuario_telegram',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
