# Generated by Django 2.2.4 on 2021-02-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0002_usuarios_usuario_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='ver_notificaciones',
            field=models.BooleanField(default=True),
        ),
    ]
